name: compass_v2
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

  flutter_compass: ^0.5.0

  google_maps_flutter: ^1.0.6

  location: ^3.1.0

  permission_handler: ^5.0.1+1

  sqflite: ^1.3.2+1

  path_provider: ^1.6.24

  http: ^0.12.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - image/compass_img.png
    - image/cursor.png
    - lang/en.json
    - lang/ru.json
