name: Test_and_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/setup-java@v1
       with: {java-version: 1.8}
     - uses: subosito/flutter-action@v1
       with:
         channel: "stable"
     - uses: actions/checkout@v2
     - run: flutter pub get

     - run: flutter build apk --release
     
